export const surpriseMePrompts = [
    "A bustling street market during Diwali, filled with colorful lights and decorations",
    "A serene yoga session in the Himalayan mountains at sunrise",
    "A Bollywood dance party with dancers in vibrant traditional attire",
    "A chai-wallah serving tea in a busy marketplace",
    "A beautiful rangoli design made with colorful powders during a festival",
    "A group of friends celebrating Holi, throwing vibrant colored powders in the air",
    "A Kathak dancer performing under the moonlight in a historical palace",
    "A lively bazaar with stalls selling spices, textiles, and handmade crafts",
    "A traditional Indian wedding with ornate decorations and intricate henna designs",
    "A Rajasthani puppet show telling a magical story",
    "A peaceful meditation session by the Ganges River at dawn",
    "A royal procession with elephants and decorated chariots",
    "A vibrant street procession during Ganesh Chaturthi with dancing and music",
    "A Durga Puja celebration with intricately designed pandals",
    "A cozy corner in an Indian library filled with ancient scriptures",
    "A rural village scene with women carrying water pots on their heads",
    "A traditional Indian boat race during a festival",
    "A traditional Indian village fair with folk music and dance",
    "A colorful kite festival in the sky during Makar Sankranti",
    "An armchair in the shape of an avocado",
    "A surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers",
    "A bowl of soup that looks like a monster, knitted out of wool",
    "A plush toy robot sitting against a yellow wall",
    "A synthwave style sunset above the reflecting water of the sea, digital art",
    "Two futuristic towers with a skybridge covered in lush foliage, digital art",
    "A 3D render of a rainbow-colored hot air balloon flying above a reflective lake",
    "A comic book cover of a superhero wearing headphones",
    "A centered explosion of colorful powder on a black background",
    "A photo of a Samoyed dog with its tongue out hugging a white Siamese cat",
    "A photo of a white fur monster standing in a purple room",
    "A pencil and watercolor drawing of a bright city in the future with flying cars",
    "A sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art",
    "A fortune-telling shiba inu reading your fate in a giant hamburger, digital art",
    "A sea otter with a pearl earring by Johannes Vermeer",
    "An oil pastel drawing of an annoyed cat in a spaceship",
    "A painting of a fox in the style of Starry Night",
    "A bowl of soup that looks like a monster, knitted out of wool",
    "A plush toy robot sitting against a yellow wall",
    "A synthwave style sunset above the reflecting water of the sea, digital art",
    "Two futuristic towers with a skybridge covered in lush foliage, digital art",
    "A 3D render of a rainbow colored hot air balloon flying above a reflective lake",
    "A comic book cover of a superhero wearing headphones",
    "A centered explosion of colorful powder on a black background",
    "A photo of a Samoyed dog with its tongue out hugging a white Siamese cat",
    "A photo of a white fur monster standing in a purple room",
    "A photo of Michelangelo's sculpture of David wearing headphones DJing",
    "A Samurai riding a Horse on Mars, lomography",
    "A modern, sleek Cadillac drives along the Gardiner Expressway with downtown Toronto in the background, with a lens flare, 50mm photography",
    "A realistic photograph of a young woman with blue eyes and blonde hair",
    "A man standing in front of a stargate to another dimension",
];
